In [3]:
# Import libraries
import os, sys
from glob import glob
from utils import stack_features, word2sense, regression, cv_regression_w2s, image_to_tensor, Subject
import numpy as np

In [6]:
# Stack data
rois = ['LOC', 'PPA', 'EVC']
layers = ['conv5', 'fc6']

roi_mean = []
for roi in rois:
    fmri_path = "predicted_" + roi + "_" + layer
    fmri_path = os.path.join(os.getcwd(), fmri_path) 
    voxel_regressor = stack_features(fmri_path, fmri=True)

    cnn_path = os.path.join('features_' + layer + '.pth')
    cnn_regressor = stack_features(cnn_path, fmri=False)

    # Run cv regression for w2s prediction
    w2s_file = "ThingsWrd2Sns.txt"
    _, w2s_embeddings = word2sense(w2s_file)

    voxel_mean_r = cv_regression_w2s(voxel_regressor, w2s_embeddings, fit=None, k=9, l2=0.0, pc=10)
    #cnn_mean_r = cv_regression_w2s(cnn_regressor, w2s_embeddings, fit=None, k=9, l2=0.0, pc=10)
    roi_mean.append(voxel_mean_r)

print(np.diff(np.array(roi_mean)))

/home/chan21/projects/semanticdimensionality/kh/object2vec_encoder_python/utils.py:230: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/home/chan21/projects/semanticdimensionality/kh/object2vec_encoder_python/utils.py:230: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/home/chan21/projects/semanticdimensionality/kh/object2vec_encoder_python/utils.py:230: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/home/chan21/projects/semanticdimensionality/kh/object2vec_encoder_python/utils.py:230: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/home/chan21/projects/semanticdimensionality/kh/object2vec_encoder_python/utils.py:230: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/home/chan21/projects/semanticdimensionality/kh/object2

[[-0.07362888 -0.10809692  0.03960174 ...  0.1055311  -0.03186558
   0.02904531]
 [-0.08535314  0.00229703  0.00798342 ...  0.17592739 -0.0558146
   0.04170269]
 [-0.02161939 -0.06379507 -0.00327384 ...  0.08902096 -0.01169642
  -0.03241714]]


/home/chan21/projects/semanticdimensionality/kh/object2vec_encoder_python/utils.py:230: RuntimeWarning: invalid value encountered in true_divide
  zs = lambda v: (v - v.mean(0)) / v.std(0)
/home/chan21/projects/semanticdimensionality/kh/object2vec_encoder_python/utils.py:53: RuntimeWarning: Mean of empty slice
  mean_r = np.nanmean(rs, axis=0) # mean across k folds


In [16]:
print(np.array(roi_mean).shape)
roi_mean = np.array(roi_mean)
print(roi_mean[0, :])
print(roi_mean[1, :])
print(roi_mean[2, :])
print(np.subtract(roi_mean[0, :], roi_mean[1, :]))
print(np.subtract(roi_mean[1, :], roi_mean[2, :]))
print(np.subtract(roi_mean[0, :], roi_mean[2, :]))

print(np.nanmean(np.subtract(roi_mean[0, :], roi_mean[1, :])))
print(np.nanmean(np.subtract(roi_mean[1, :], roi_mean[2, :])))
print(np.nanmean(np.subtract(roi_mean[0, :], roi_mean[2, :])))


(3, 2250)
[0.19455688 0.12092801 0.01283108 ... 0.05358288 0.0217173  0.05076261]
[0.15132378 0.06597064 0.06826767 ... 0.12650547 0.07069087 0.11239356]
[0.13627015 0.11465077 0.05085569 ... 0.10847946 0.09678303 0.06436589]
[ 0.0432331   0.05495737 -0.05543659 ... -0.07292259 -0.04897357
 -0.06163095]
[ 0.01505363 -0.04868012  0.01741198 ...  0.01802601 -0.02609216
  0.04802767]
[ 0.05828673  0.00627724 -0.03802461 ... -0.05489658 -0.07506573
 -0.01360328]
0.00048174771977799706
0.005097691757124868
0.0055794394769028656
